### ISSUE TITLE
Value from dictionary

### ISSUE THREAD

**Issue by pavankv1** [T4P4N/t4p4n.github.io#1]
In template i had given like this i want to get only one project value as number.
<td class="c1">{{ row.name }}</td>
      <td class="c1">{{ row.id }}</td>
        {% for heading in project_list %}
        <td class="c1"> {% if heading in row.projects %} {{row.projects}} {% else %} 0 {% endif %}</td>>
        {% endfor %}

output:
{'Example Project 2': 25, 'Tool Makers': '75', 'New Project': '75'}

my output looks like this but i need 25 as output

what can I change in if condition to achieve my output ,can anyone pls help me to sort it.

**Comment by T4P4N** [comment]
i saw your dm on telegram.
